// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/illinoisdpi/go-service-template/api/users"
	"github.com/illinoisdpi/go-service-template/configs"
	"github.com/illinoisdpi/go-service-template/db"
	"github.com/illinoisdpi/go-service-template/db/sqlc"
	"github.com/jackc/pgx/v5/pgxpool"
	"log/slog"
)

// Injectors from wire.go:

func InitializeLogger() *slog.Logger {
	logger := configs.NewLogger()
	return logger
}

func InitializeDBPool() *pgxpool.Pool {
	pool := db.NewDBPool()
	return pool
}

func InitializeDBQueries() *sqlc.Queries {
	pool := InitializeDBPool()
	queries := db.NewQueries(pool)
	return queries
}

func InitializeUserService() *users.UserService {
	logger := InitializeLogger()
	queries := InitializeDBQueries()
	userService := users.NewUserService(logger, queries)
	return userService
}
