// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package sqlc

import (
	"context"
)

const listUsers = `-- name: ListUsers :many
SELECT "ID"
FROM "USERS"
`

func (q *Queries) ListUsers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ID string
		if err := rows.Scan(&ID); err != nil {
			return nil, err
		}
		items = append(items, ID)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
